add donors files partitioned in sub-folders
gitcoinco/allo-indexer pull request #81
Opened 2023-05-23 17:03 UTC by gravityblast

2023-05-23 17:34 UTC, vacekj submitted a review, later dismissed

2023-05-24 06:47 UTC, boudra requested changes

2023-05-24 06:47 UTC, boudra commented on src/indexer/handleEvent.ts
> +          db.collection(`donors/${donorPartitionedPath}`).insert({
aren't we calling them contributors everywhere else in the app?

2023-05-24 06:47 UTC, boudra commented on src/indexer/handleEvent.ts
> +        const donorPartitionedPath = vote.voter
I don't understand this, what does it do? I can try it later, reviewing on mobile

2023-05-24 06:47 UTC, boudra commented on src/indexer/handleEvent.ts
> +              canonicalId: application.metadata.application.project.id,
is this also something we want to rename as well? projectId to canonicalId?

2023-05-24 09:56 UTC, boudra approved these changes

2023-05-24 20:34 UTC, hmrtn approved these changes

2023-05-24 20:36 UTC, merged